model:
    n_chanels_output_layer1: 10
    n_chanels_output_layer2: 20
    filtersize_layer1: 5
    filtersize_layer2: 5
    number_of_neurons_dense_layer1: 50
    number_of_neurons_dense_layer2: 10

training:
    momentum: 0.05
    learning_rate: 0.01
    batch_size_train: 64 
   
                           

